// All 99 languages supported by OpenAI Whisper, sourced from
// https://github.com/openai/whisper/blob/main/whisper/tokenizer.py
// Each entry stores the ISO code, the English name, and the endonym
// (autoglot — the language's own name in its own script). The endonym
// keeps the picker readable for native speakers regardless of the UI
// language; the English name keeps it searchable for everyone else.

export interface WhisperLanguage {
  code: string;
  english: string;
  endonym: string;
}

export const WHISPER_LANGUAGES: WhisperLanguage[] = [
  { code: 'af', english: 'Afrikaans', endonym: 'Afrikaans' },
  { code: 'sq', english: 'Albanian', endonym: 'Shqip' },
  { code: 'am', english: 'Amharic', endonym: 'አማርኛ' },
  { code: 'ar', english: 'Arabic', endonym: 'العربية' },
  { code: 'hy', english: 'Armenian', endonym: 'Հայերեն' },
  { code: 'as', english: 'Assamese', endonym: 'অসমীয়া' },
  { code: 'az', english: 'Azerbaijani', endonym: 'Azərbaycan' },
  { code: 'ba', english: 'Bashkir', endonym: 'Башҡортса' },
  { code: 'eu', english: 'Basque', endonym: 'Euskara' },
  { code: 'be', english: 'Belarusian', endonym: 'Беларуская' },
  { code: 'bn', english: 'Bengali', endonym: 'বাংলা' },
  { code: 'bs', english: 'Bosnian', endonym: 'Bosanski' },
  { code: 'br', english: 'Breton', endonym: 'Brezhoneg' },
  { code: 'bg', english: 'Bulgarian', endonym: 'Български' },
  { code: 'my', english: 'Burmese', endonym: 'မြန်မာ' },
  { code: 'yue', english: 'Cantonese', endonym: '粵語' },
  { code: 'ca', english: 'Catalan', endonym: 'Català' },
  { code: 'zh', english: 'Chinese', endonym: '中文' },
  { code: 'hr', english: 'Croatian', endonym: 'Hrvatski' },
  { code: 'cs', english: 'Czech', endonym: 'Čeština' },
  { code: 'da', english: 'Danish', endonym: 'Dansk' },
  { code: 'nl', english: 'Dutch', endonym: 'Nederlands' },
  { code: 'en', english: 'English', endonym: 'English' },
  { code: 'et', english: 'Estonian', endonym: 'Eesti' },
  { code: 'fo', english: 'Faroese', endonym: 'Føroyskt' },
  { code: 'fi', english: 'Finnish', endonym: 'Suomi' },
  { code: 'fr', english: 'French', endonym: 'Français' },
  { code: 'gl', english: 'Galician', endonym: 'Galego' },
  { code: 'ka', english: 'Georgian', endonym: 'ქართული' },
  { code: 'de', english: 'German', endonym: 'Deutsch' },
  { code: 'el', english: 'Greek', endonym: 'Ελληνικά' },
  { code: 'gu', english: 'Gujarati', endonym: 'ગુજરાતી' },
  { code: 'ht', english: 'Haitian Creole', endonym: 'Kreyòl Ayisyen' },
  { code: 'ha', english: 'Hausa', endonym: 'Hausa' },
  { code: 'haw', english: 'Hawaiian', endonym: 'ʻŌlelo Hawaiʻi' },
  { code: 'he', english: 'Hebrew', endonym: 'עברית' },
  { code: 'hi', english: 'Hindi', endonym: 'हिन्दी' },
  { code: 'hu', english: 'Hungarian', endonym: 'Magyar' },
  { code: 'is', english: 'Icelandic', endonym: 'Íslenska' },
  { code: 'id', english: 'Indonesian', endonym: 'Bahasa Indonesia' },
  { code: 'it', english: 'Italian', endonym: 'Italiano' },
  { code: 'ja', english: 'Japanese', endonym: '日本語' },
  { code: 'jw', english: 'Javanese', endonym: 'Basa Jawa' },
  { code: 'kn', english: 'Kannada', endonym: 'ಕನ್ನಡ' },
  { code: 'kk', english: 'Kazakh', endonym: 'Қазақша' },
  { code: 'km', english: 'Khmer', endonym: 'ខ្មែរ' },
  { code: 'ko', english: 'Korean', endonym: '한국어' },
  { code: 'lo', english: 'Lao', endonym: 'ລາວ' },
  { code: 'la', english: 'Latin', endonym: 'Latina' },
  { code: 'lv', english: 'Latvian', endonym: 'Latviešu' },
  { code: 'ln', english: 'Lingala', endonym: 'Lingála' },
  { code: 'lt', english: 'Lithuanian', endonym: 'Lietuvių' },
  { code: 'lb', english: 'Luxembourgish', endonym: 'Lëtzebuergesch' },
  { code: 'mk', english: 'Macedonian', endonym: 'Македонски' },
  { code: 'mg', english: 'Malagasy', endonym: 'Malagasy' },
  { code: 'ms', english: 'Malay', endonym: 'Bahasa Melayu' },
  { code: 'ml', english: 'Malayalam', endonym: 'മലയാളം' },
  { code: 'mt', english: 'Maltese', endonym: 'Malti' },
  { code: 'mi', english: 'Maori', endonym: 'Māori' },
  { code: 'mr', english: 'Marathi', endonym: 'मराठी' },
  { code: 'mn', english: 'Mongolian', endonym: 'Монгол' },
  { code: 'ne', english: 'Nepali', endonym: 'नेपाली' },
  { code: 'no', english: 'Norwegian', endonym: 'Norsk' },
  { code: 'nn', english: 'Nynorsk', endonym: 'Nynorsk' },
  { code: 'oc', english: 'Occitan', endonym: 'Occitan' },
  { code: 'ps', english: 'Pashto', endonym: 'پښتو' },
  { code: 'fa', english: 'Persian', endonym: 'فارسی' },
  { code: 'pl', english: 'Polish', endonym: 'Polski' },
  { code: 'pt', english: 'Portuguese', endonym: 'Português' },
  { code: 'pa', english: 'Punjabi', endonym: 'ਪੰਜਾਬੀ' },
  { code: 'ro', english: 'Romanian', endonym: 'Română' },
  { code: 'ru', english: 'Russian', endonym: 'Русский' },
  { code: 'sa', english: 'Sanskrit', endonym: 'संस्कृतम्' },
  { code: 'sr', english: 'Serbian', endonym: 'Српски' },
  { code: 'sn', english: 'Shona', endonym: 'ChiShona' },
  { code: 'sd', english: 'Sindhi', endonym: 'سنڌي' },
  { code: 'si', english: 'Sinhala', endonym: 'සිංහල' },
  { code: 'sk', english: 'Slovak', endonym: 'Slovenčina' },
  { code: 'sl', english: 'Slovenian', endonym: 'Slovenščina' },
  { code: 'so', english: 'Somali', endonym: 'Soomaali' },
  { code: 'es', english: 'Spanish', endonym: 'Español' },
  { code: 'su', english: 'Sundanese', endonym: 'Basa Sunda' },
  { code: 'sw', english: 'Swahili', endonym: 'Kiswahili' },
  { code: 'sv', english: 'Swedish', endonym: 'Svenska' },
  { code: 'tl', english: 'Tagalog', endonym: 'Tagalog' },
  { code: 'tg', english: 'Tajik', endonym: 'Тоҷикӣ' },
  { code: 'ta', english: 'Tamil', endonym: 'தமிழ்' },
  { code: 'tt', english: 'Tatar', endonym: 'Татарча' },
  { code: 'te', english: 'Telugu', endonym: 'తెలుగు' },
  { code: 'th', english: 'Thai', endonym: 'ไทย' },
  { code: 'bo', english: 'Tibetan', endonym: 'བོད་སྐད་' },
  { code: 'tr', english: 'Turkish', endonym: 'Türkçe' },
  { code: 'tk', english: 'Turkmen', endonym: 'Türkmençe' },
  { code: 'uk', english: 'Ukrainian', endonym: 'Українська' },
  { code: 'ur', english: 'Urdu', endonym: 'اردو' },
  { code: 'uz', english: 'Uzbek', endonym: 'Oʻzbekcha' },
  { code: 'vi', english: 'Vietnamese', endonym: 'Tiếng Việt' },
  { code: 'cy', english: 'Welsh', endonym: 'Cymraeg' },
  { code: 'yi', english: 'Yiddish', endonym: 'ייִדיש' },
  { code: 'yo', english: 'Yoruba', endonym: 'Yorùbá' },
];

export function whisperLanguageLabel(lang: WhisperLanguage): string {
  return lang.english === lang.endonym
    ? lang.english
    : `${lang.english} — ${lang.endonym}`;
}
